name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/wasmcloud/cache/wasmcloud

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1 # abort caching attempt if it's slow

runs:
  using: composite
  steps:
  # Install Nix
  - uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3
    with:
      extra-conf: |
        accept-flake-config = true

  # Setup magic Nix cache
  - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b

  # Setup Cachix cache
  - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc
    continue-on-error: true
    with:
      name: wasmcloud
      authToken: '${{ inputs.cachixAuthToken }}'
